services:
  tensorflow:
    image: outfit_env:1.0
    container_name: tf_cpu
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./src/model_impl:/temp
      - ./data:/data
    working_dir: /temp
    entrypoint: ["python", "app.py"]
    depends_on:
      - outfit_db
    networks:
      - outfit_network
    restart: unless-stopped
  outfit_db:
    image: mongo:8.0
    container_name: outfit_db
    ports:
    - "27022:27017"
    networks:
      - outfit_network
    volumes:
      - outfit:/data/db
    restart: always
networks:
  outfit_network:
    name: outfit_network
volumes:
  outfit:
    name: outfit
    driver: local